language: android

android:
  components:
    - android-30
    - build-tools-29.0.3
    - tools
    - platform-tools
    - extra-android-m2repository

before_install:
  - yes | $ANDROID_HOME/tools/bin/sdkmanager "build-tools;29.0.3"
  - chmod +x gradlew

script:
  - ./gradlew clean assembleDebug assembleRelease testDebug